# Generated by Django 5.1.15 on 2026-09-22 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('visitors', models.PositiveIntegerField(default=0, verbose_name='Visiteurs')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='Pages vues')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Commandes')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name="Chiffre d'affaires (FCFA)")),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='Nouveaux inscrits')),
            ],
            options={
                'verbose_name': 'Statistique journaliere',
                'verbose_name_plural': 'Statistiques journalieres',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vue produit',
                'verbose_name_plural': 'Vues produits',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300, verbose_name='Recherche')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Nb resultats')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recherche',
                'verbose_name_plural': 'Recherches',
                'ordering': ['-searched_at'],
            },
        ),
    ]
