# Generated by Django 5.1.15 on 2026-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ONIZOUKA SHOP', max_length=150, verbose_name='Nom de la boutique')),
                ('company_name', models.CharField(default='ONIZOUKA SHOP SARL', max_length=200, verbose_name='Raison sociale légale')),
                ('nif', models.CharField(blank=True, default='085123456M', max_length=100, verbose_name="Numéro d'Identification Fiscale (NIF)")),
                ('rccm', models.CharField(blank=True, default='MA-BKO-2024-B-12345', max_length=100, verbose_name='Registre du Commerce (RCCM)')),
                ('address', models.CharField(default="Hamdallaye ACI 2000, près de la place de l'Obélisque, Bamako, Mali", max_length=255, verbose_name='Adresse Showroom')),
                ('phone_contact', models.CharField(default='+223 70 00 00 00', max_length=50, verbose_name='Téléphone Service Client')),
                ('phone_whatsapp', models.CharField(default='+223 70 00 00 00', max_length=50, verbose_name='WhatsApp Commercial')),
                ('email_contact', models.EmailField(default='contact@onizoukashop.com', max_length=254, verbose_name='Email officiel')),
                ('email_orders', models.EmailField(default='direction@onizoukashop.com', max_length=254, verbose_name='Email alertes commandes Direction')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('default_delivery_fee', models.DecimalField(decimal_places=0, default=2000, max_digits=10, verbose_name='Frais de livraison forfaitaires Bamako (FCFA)')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=0, default=500000, max_digits=12, verbose_name='Seuil de livraison gratuite (FCFA)')),
                ('delivery_delay_text', models.CharField(default='Sous 24h ouvrées', max_length=100, verbose_name='Délai moyen affiché')),
                ('store_pickup_active', models.BooleanField(default=True, verbose_name='Activer retrait gratuit magasin 15 min')),
                ('orange_money_number', models.CharField(default='+223 70 00 00 00', max_length=50, verbose_name='Numéro / Code Marchand Orange Money')),
                ('wave_number', models.CharField(default='+223 70 00 00 00', max_length=50, verbose_name='Numéro Wave Mobile Money')),
                ('cash_on_delivery_active', models.BooleanField(default=True, verbose_name='Activer le paiement en espèces à la livraison')),
                ('default_min_stock_alert', models.PositiveIntegerField(default=5, verbose_name='Seuil alerte rupture par défaut')),
                ('block_order_on_out_of_stock', models.BooleanField(default=True, verbose_name="Bloquer l'achat si rupture de stock")),
                ('email_notifications_active', models.BooleanField(default=True, verbose_name='Envoyer les emails automatiques aux clients')),
                ('whatsapp_notifications_active', models.BooleanField(default=True, verbose_name='Activer les alertes rapides WhatsApp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres de la Boutique',
                'verbose_name_plural': 'Paramètres de la Boutique',
            },
        ),
    ]
