# Generated by Django 5.1.15 on 2026-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='flash_sale_active',
            field=models.BooleanField(default=True, verbose_name="Activer la section Ventes Flash sur l'accueil"),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='flash_sale_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin du compte à rebours'),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='flash_sale_subtitle',
            field=models.CharField(default='Tarifs remisés disponibles immédiatement en stock à Bamako', max_length=255, verbose_name='Sous-titre descriptif'),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='flash_sale_title',
            field=models.CharField(default='Ventes Flash de la Semaine', max_length=150, verbose_name='Titre de la Vente Flash'),
        ),
        migrations.AlterField(
            model_name='shopsetting',
            name='address',
            field=models.CharField(default='Grand Marché de Bamako, Dabanani, Bamako, Mali', max_length=255, verbose_name='Adresse Boutique'),
        ),
        migrations.AlterField(
            model_name='shopsetting',
            name='orange_money_number',
            field=models.CharField(default='+223 92 67 37 99', max_length=50, verbose_name='Numéro / Code Marchand Orange Money'),
        ),
        migrations.AlterField(
            model_name='shopsetting',
            name='phone_contact',
            field=models.CharField(default='+223 92 67 37 99', max_length=50, verbose_name='Téléphone Service Client'),
        ),
        migrations.AlterField(
            model_name='shopsetting',
            name='phone_whatsapp',
            field=models.CharField(default='+223 92 67 37 99', max_length=50, verbose_name='WhatsApp Commercial'),
        ),
        migrations.AlterField(
            model_name='shopsetting',
            name='wave_number',
            field=models.CharField(default='+223 92 67 37 99', max_length=50, verbose_name='Numéro Wave Mobile Money'),
        ),
    ]
