# Generated by Django 5.1.15 on 2026-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_shopsetting_flash_sale_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='meta_domain_verification',
            field=models.CharField(blank=True, default='', help_text="Code meta name='facebook-domain-verification' fourni par Meta Business Suite", max_length=100, verbose_name='Code de vérification de domaine Meta'),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='meta_pixel_id',
            field=models.CharField(blank=True, default='', help_text='Identifiant numérique Meta Pixel à 15-16 chiffres fourni par Meta Events Manager', max_length=50, verbose_name='ID Pixel Facebook (Meta)'),
        ),
    ]
