# Generated by Django 5.1.15 on 2026-09-24 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email vérifié'),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email cible')),
                ('code', models.CharField(max_length=6, verbose_name='Code PIN à 6 chiffres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('is_used', models.BooleanField(default=False, verbose_name='Déjà utilisé')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives de saisie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code OTP Email',
                'verbose_name_plural': 'Codes OTP Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
