# Generated by Django 5.1.15 on 2026-09-22 18:03

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Logo')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Material Icons name', max_length=50, verbose_name='Icone')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta titre SEO')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='Meta description SEO')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Categorie parente')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nom du produit')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL slug')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Reference SKU')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Description courte')),
                ('description', models.TextField(verbose_name='Description complete')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Specs techniques en JSON {"Capacite": "350L", "Classe": "A+++"}', verbose_name='Specifications techniques')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix normal (FCFA)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix promo (FCFA)')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de revient (FCFA)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantite en stock')),
                ('min_stock', models.PositiveIntegerField(default=5, verbose_name='Stock minimum (alerte)')),
                ('track_stock', models.BooleanField(default=True, verbose_name='Gerer le stock')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Poids (kg)')),
                ('dimensions', models.CharField(blank=True, help_text='LxlxH en cm', max_length=100, verbose_name='Dimensions')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta titre SEO')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='Meta description SEO')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('out_of_stock', 'Rupture de stock'), ('coming_soon', 'Prochainement')], default='active', max_length=20, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produit vedette')),
                ('is_new', models.BooleanField(default=True, verbose_name='Nouveau')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Derniere modif')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.brand', verbose_name='Marque')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produits',
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'avis")),
                ('body', models.TextField(verbose_name="Contenu de l'avis")),
                ('is_verified', models.BooleanField(default=False, verbose_name='Achat verifie')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approuve')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='shop_produc_slug_76971b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active'], name='shop_produc_status_dbca87_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='shop_produc_categor_6c2d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='shop_produc_price_3b79b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='shop_produc_stock_da91c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
    ]
